server:
#  端口
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: root
    hikari:
      #连接池名字
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间,默认600000（10分钟）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间,0表示永久存活，默认180000（30分钟）
      max-lifetime: 180000
      #连接超时时间,默认30000(30秒)
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    #超时时间
    connect-timeout:
    #服务器地址
    host: 8.130.100.189
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
    password: 19990410zjp
    lettuce:
      pool:
        #最大连接数, 默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最小空闲连接
        min-idle: 5

#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.xxx.server.pojo
  #自动驼峰命名
  configuration:
    map-underscore-to-camel-case: false
  #mybatis SQL打印
logging:
  level:
    com.xxx.server.mapper: debug

jwt:
# JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
