server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
  # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: QIUTGVIXNQLZCAMO
    # 发送者邮箱地址
    username: 15328731596@163.com
    # 端口（不同邮箱端口号不同）
    port: 25
  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: admin
    # 密码
    password: 19990410zjp
    # 服务器地址
    host: 121.4.145.102
    # 端口
    port: 5672

